#define TIMOD_CTRL  0x200u
#define TIMOD_SHIFT 0x400u
#define TIMOD_FCTN  0x800u

#define TIKEY_Equals 0u
#define TIKEY_Space  1u
#define TIKEY_Enter  2u
#define TIKEY_Fctn   4u
#define TIKEY_Shift  5u
#define TIKEY_Ctrl   6u
#define TIKEY_Period 8u
#define TIKEY_L	     9u
#define TIKEY_O	    10u
#define TIKEY_9	    11u
#define TIKEY_2	    12u
#define TIKEY_S	    13u
#define TIKEY_W	    14u
#define TIKEY_X	    15u
#define TIKEY_Comma 16u
#define TIKEY_K	    17u
#define TIKEY_I	    18u
#define TIKEY_8	    19u
#define TIKEY_3	    20u
#define TIKEY_D	    21u
#define TIKEY_E	    22u
#define TIKEY_C	    23u
#define TIKEY_M	    24u
#define TIKEY_J	    25u
#define TIKEY_U	    26u
#define TIKEY_7	    27u
#define TIKEY_4	    28u
#define TIKEY_F	    29u
#define TIKEY_R	    30u
#define TIKEY_V	    31u
#define TIKEY_N	    32u
#define TIKEY_H	    33u
#define TIKEY_Y	    34u
#define TIKEY_6	    35u
#define TIKEY_5	    36u
#define TIKEY_G	    37u
#define TIKEY_T	    38u
#define TIKEY_B	    39u
#define TIKEY_Slash 40u
#define TIKEY_Semic 41u
#define TIKEY_P	    42u
#define TIKEY_0	    43u
#define TIKEY_1	    44u
#define TIKEY_A	    45u
#define TIKEY_Q	    46u
#define TIKEY_Z	    47u
